# Generated by Django 5.1.8 on 2025-04-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=4)),
                ('status', models.IntegerField(choices=[(1, 'Waiting'), (2, 'Playing'), (3, 'Finished')])),
            ],
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='won',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(choices=[(0, '予選'), (1, '準々決勝'), (2, '準決勝'), (3, '決勝')])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='tournament.game')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to='tournament.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='games',
            field=models.ManyToManyField(through='tournament.TournamentGame', to='tournament.game'),
        ),
    ]
