# Generated by Django 5.1.8 on 2025-04-30 07:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_gameplayer_won_tournamentgame_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='game',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='games',
        ),
        migrations.RemoveField(
            model_name='tournamentgame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tournamentgame',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='name',
        ),
        migrations.AddField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_type',
            field=models.IntegerField(choices=[(0, 'Practice'), (1, 'Singles'), (2, 'Double')], default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'Playing'), (3, 'Finished')], default=1),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_status', models.IntegerField(choices=[(1, 'Waiting'), (2, 'Playing'), (3, 'Finished')], default=1)),
                ('round', models.IntegerField(choices=[(0, 'Preliminary'), (1, 'Quarterfinal'), (2, 'Semifinal'), (3, 'Final')], default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_as_palyer2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournament.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tournament.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1_matches', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2_matches', to='tournament.team'),
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_round', models.IntegerField(choices=[(0, 'Preliminary'), (1, 'Quarterfinal'), (2, 'Semifinal'), (3, 'Final')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_entries', to='tournament.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(through='tournament.TournamentPlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GamePlayer',
        ),
        migrations.DeleteModel(
            name='TournamentGame',
        ),
    ]
