# Generated by Django 5.1.8 on 2025-04-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_gameplayer_game_remove_tournament_games_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
