# Generated by Django 5.1.8 on 2025-05-09 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_tournament_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='size',
        ),
        migrations.AlterField(
            model_name='team',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_as_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='match_type',
            field=models.IntegerField(choices=[(0, 'Practice'), (1, 'Singles'), (2, 'Doubles')], default=1),
        ),
    ]
