# Generated by Django 5.1.9 on 2025-05-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_tournament_size_alter_team_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_ready_to_start',
            field=models.BooleanField(default=False),
        ),
    ]
