# Generated by Django 5.1.9 on 2025-05-13 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_is_ready_to_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.match'),
        ),
    ]
