# Generated by Django 5.1.9 on 2025-05-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_tournament_match_size_alter_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_size',
            field=models.IntegerField(choices=[(2, 'Two'), (4, 'Four')], default=4),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='match_size',
            field=models.IntegerField(choices=[(2, 'Two'), (4, 'Four')], default=4),
        ),
    ]
