# Generated by Django 5.1.9 on 2025-05-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_match_match_size_alter_tournament_match_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ball_number',
            field=models.IntegerField(default=1),
        ),
    ]
