# Generated by Django 5.1.9 on 2025-05-28 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_tournament_ball_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.match'),
        ),
    ]
