# Generated by Django 5.1.10 on 2025-06-06 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_alter_score_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_size',
        ),
    ]
