services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command:
      sleep infinity
    ports:
      - "3000:3000"

volumes:
  node_modules:
