FROM nginx:1.27.5-bookworm

COPY ./nginx/certs/cert.pem /etc/nginx/certs/cert.pem
COPY ./nginx/certs/key.pem /etc/nginx/certs/key.pem
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

USER root
