services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=${DEBUG:-False}
    ports: #open for https?
      - "8000:8000"
      - "443:443"
    restart:
      always
    volumes: #? need to change
      - .:/app
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
      /bin/bash -c "cd /app/app && \
      mkdir -p certs && \
      openssl req -x509 -newkey rsa:4096 -keyout ./certs/key.pem -out ./certs/cert.pem -days 365 -nodes -batch -subj '/CN=localhost' -addext 'subjectAltName=DNS:localhost,IP:127.0.0.1' && \
      python manage.py migrate && \
      python manage.py collectstatic --noinput && \
      daphne -e ssl:443:privateKey=./certs/key.pem:certKey=./certs/cert.pem app.asgi:application"

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:7.4-alpine
    restart: always
    volumes:
      - redis_channel_layer:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_volume:
    name: transcendence_db_volume
  redis_channel_layer:
    name: transcendence_channle_layer_volume

networks:
  backend:
    name: transcendence
