# Generated by Django 5.1.9 on 2025-05-26 08:24

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_is_online_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to=user.models.get_avatar_image_path, verbose_name='Avatar'),
        ),
    ]
