# Generated by Django 5.1.7 on 2025-03-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamemodel_player1_alter_gamemodel_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentplayermodel',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentroundmodel',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentplayermodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tournamentroundmodel',
            name='games',
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TournamentModel',
        ),
        migrations.DeleteModel(
            name='TournamentPlayerModel',
        ),
        migrations.DeleteModel(
            name='TournamentRoundModel',
        ),
    ]
