# Generated by Django 5.1.7 on 2025-03-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_tournamentplayermodel_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='status',
        ),
    ]
