# Generated by Django 5.1.7 on 2025-03-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_gamemodel_scheduled_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="<class 'datetime.time'>", max_length=255)),
                ('size', models.IntegerField(default=4)),
                ('games', models.ManyToManyField(blank=True, to='game.gamemodel')),
            ],
        ),
    ]
