# Generated by Django 5.1.7 on 2025-03-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
