# Generated by Django 5.1.8 on 2025-04-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gameroom_player3_gameroom_player3_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player3_score',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player4_score',
        ),
    ]
