# Generated by Django 5.1.8 on 2025-04-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_gameroom_player3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournament',
            new_name='TournamentModel',
        ),
    ]
