"""
This type stub file was generated by pyright.
"""

class ChannelLayerManager:
    """
    Takes a settings dictionary of backends and initialises them on request.
    """
    def __init__(self) -> None:
        ...
    
    @property
    def configs(self): # -> Any | dict[Any, Any]:
        ...
    
    def make_backend(self, name): # -> Any:
        """
        Instantiate channel layer.
        """
        ...
    
    def make_test_backend(self, name): # -> Any:
        """
        Instantiate channel layer using its test config.
        """
        ...
    
    def __getitem__(self, key):
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    
    def set(self, key, layer): # -> None:
        """
        Sets an alias to point to a new ChannelLayerWrapper instance, and
        returns the old one that it replaced. Useful for swapping out the
        backend during tests.
        """
        ...
    


class BaseChannelLayer:
    """
    Base channel layer class that others can inherit from, with useful
    common functionality.
    """
    MAX_NAME_LENGTH = ...
    def __init__(self, expiry=..., capacity=..., channel_capacity=...) -> None:
        ...
    
    def compile_capacities(self, channel_capacity): # -> list[Any]:
        """
        Takes an input channel_capacity dict and returns the compiled list
        of regexes that get_capacity will look for as self.channel_capacity
        """
        ...
    
    def get_capacity(self, channel): # -> int:
        """
        Gets the correct capacity for the given channel; either the default,
        or a matching result from channel_capacity. Returns the first matching
        result; if you want to control the order of matches, use an ordered dict
        as input.
        """
        ...
    
    def match_type_and_length(self, name): # -> bool:
        ...
    
    channel_name_regex = ...
    group_name_regex = ...
    invalid_name_error = ...
    def require_valid_channel_name(self, name, receive=...): # -> Literal[True]:
        ...
    
    def require_valid_group_name(self, name): # -> Literal[True]:
        ...
    
    def valid_channel_names(self, names, receive=...): # -> Literal[True]:
        ...
    
    def non_local_name(self, name):
        """
        Given a channel name, returns the "non-local" part. If the channel name
        is a process-specific channel (contains !) this means the part up to
        and including the !; if it is anything else, this means the full name.
        """
        ...
    
    async def send(self, channel, message):
        ...
    
    async def receive(self, channel):
        ...
    
    async def new_channel(self):
        ...
    
    async def flush(self):
        ...
    
    async def group_add(self, group, channel):
        ...
    
    async def group_discard(self, group, channel):
        ...
    
    async def group_send(self, group, message):
        ...
    
    def valid_channel_name(self, channel_name, receive=...): # -> Literal[True]:
        """
        Deprecated: Use require_valid_channel_name instead.
        """
        ...
    
    def valid_group_name(self, group_name): # -> Literal[True]:
        """
        Deprecated: Use require_valid_group_name instead..
        """
        ...
    


class InMemoryChannelLayer(BaseChannelLayer):
    """
    In-memory channel layer implementation
    """
    def __init__(self, expiry=..., group_expiry=..., capacity=..., channel_capacity=..., **kwargs) -> None:
        ...
    
    extensions = ...
    async def send(self, channel, message): # -> None:
        """
        Send a message onto a (general or specific) channel.
        """
        ...
    
    async def receive(self, channel):
        """
        Receive the first message that arrives on the channel.
        If more than one coroutine waits on the same channel, a random one
        of the waiting coroutines will get the result.
        """
        ...
    
    async def new_channel(self, prefix=...): # -> str:
        """
        Returns a new channel name that can be used by something in our
        process as a specific channel.
        """
        ...
    
    async def flush(self): # -> None:
        ...
    
    async def close(self): # -> None:
        ...
    
    async def group_add(self, group, channel): # -> None:
        """
        Adds the channel name to a group.
        """
        ...
    
    async def group_discard(self, group, channel): # -> None:
        ...
    
    async def group_send(self, group, message): # -> None:
        ...
    


def get_channel_layer(alias=...): # -> None:
    """
    Returns a channel layer by alias, or None if it is not configured.
    """
    ...

channel_layers = ...
