"""
This type stub file was generated by pyright.
"""

class BaseMiddleware:
    """
    Base class for implementing ASGI middleware.

    Note that subclasses of this are not self-safe; don't store state on
    the instance, as it serves multiple application instances. Instead, use
    scope.
    """
    def __init__(self, inner) -> None:
        """
        Middleware constructor - just takes inner application.
        """
        ...
    
    async def __call__(self, scope, receive, send):
        """
        ASGI application; can insert things into the scope and run asynchronous
        code.
        """
        ...
    


