"""
This type stub file was generated by pyright.
"""

def get_default_application(): # -> Any:
    """
    Gets the default application, set in the ASGI_APPLICATION setting.
    """
    ...

class ProtocolTypeRouter:
    """
    Takes a mapping of protocol type names to other Application instances,
    and dispatches to the right one based on protocol name (or raises an error)
    """
    def __init__(self, application_mapping) -> None:
        ...
    
    async def __call__(self, scope, receive, send):
        ...
    


class URLRouter:
    """
    Routes to different applications/consumers based on the URL path.

    Works with anything that has a ``path`` key, but intended for WebSocket
    and HTTP. Uses Django's django.urls objects for resolution -
    path() or re_path().
    """
    _path_routing = ...
    def __init__(self, routes) -> None:
        ...
    
    async def __call__(self, scope, receive, send):
        ...
    


class ChannelNameRouter:
    """
    Maps to different applications based on a "channel" key in the scope
    (intended for the Channels worker mode)
    """
    def __init__(self, application_mapping) -> None:
        ...
    
    async def __call__(self, scope, receive, send):
        ...
    


